apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: multicloud-aws-rxhv5 
  name: multicloud-aws-rxhv5-worker-us-east-1d 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: multicloud-aws-rxhv5 
      machine.openshift.io/cluster-api-machineset: multicloud-aws-rxhv5-worker-us-east-1d  
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: multicloud-aws-rxhv5 
        machine.openshift.io/cluster-api-machine-role: worker 
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: multicloud-aws-rxhv5-worker-us-east-1d
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "" 
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: multicloud-aws-rxhv5-worker-profile 
          instanceType: m6i.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-1d 
            region: us-east-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - multicloud-aws-rxhv5-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - multicloud-aws-rxhv5-private-us-east-1d
          tags:
            - name: kubernetes.io/cluster/multicloud-aws-rxhv5 
              value: owned 
          userDataSecret:
            name: worker-user-data
      taints: 
        - key: node-role.kubernetes.io/infra
          effect: NoSchedule
